from autodiag.buffer import Buffer

b = Buffer()
b.append_byte(0x01)
b.append_bytes([0x02, 0x03, 0x04])
b.append_str("Hello")
print(b.to_ascii_hex())
b2 = Buffer.from_ascii_hex("48656c6c6f")
b.prepend(b2)
b.ensure_termination()
print("Buffer contents in ASCII:", b.to_ascii())
print("Buffer contents in ASCII Hex:", b.to_ascii_hex())
print("Buffer free space:", b.get_free_space())
b3 = b.copy()
print("Copied buffer contents in ASCII:", b3.to_ascii_hex())
b4 = Buffer.new_random(10)
print("New random buffer contents in ASCII:", b4.to_ascii_hex())
b5 = Buffer.new_cycle(10, 50)
print("New cycle buffer contents in ASCII:", b5.to_ascii_hex())
b7 = Buffer.from_ascii("Test ASCII")
print("Buffer from ASCII contents in ASCII:", b7.to_ascii_hex())
b8 = Buffer.from_ascii_hex("54657374")
print("Buffer from ASCII Hex contents in ASCII:", b8.to_ascii_hex())
b.padding(20, 0xFF)
print("Buffer after padding to 20 bytes:", b.to_ascii_hex())
b9 = Buffer()
b9.append_bytes([0x01, 0x02, 0x03])
print(b9.to_ascii_hex())