/**
 * ISO 14229
 */
#ifndef __UDS_H
#define __UDS_H

#include "libautodiag/lang/all.h"
#include "libautodiag/com/vehicle_interface.h"
#include "libautodiag/com/obd/obd.h"

typedef enum {
    UDS_SERVICE_DIAGNOSTIC_SESSION_CONTROL = 0x10,
    UDS_SERVICE_ECU_RESET = 0x11,
    UDS_SERVICE_CLEAR_DIAGNOSTIC_INFORMATION = 0x14,
    UDS_SERVICE_READ_DTC_INFORMATION = 0x19,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER = 0x22,
    UDS_SERVICE_READ_MEMORY_BY_ADDRESS = 0x23,
    UDS_SERVICE_READ_SCALING_DATA_BY_IDENTIFIER = 0x24,
    UDS_SERVICE_SECURITY_ACCESS = 0x27,
    UDS_SERVICE_COMMUNICATION_CONTROL = 0x28,
    UDS_SERVICE_AUTHENTICATION = 0x29,
    UDS_SERVICE_READ_DATA_BY_PERIOD_IDENTIFIER = 0x2A,
    UDS_SERVICE_READ_FRESH_DATA_BY_IDENTIFIER = 0x2C,
    UDS_SERVICE_DYNAMICALLY_DEFINE_DATA_IDENTIFIER = 0x2C,
    UDS_SERVICE_WRITE_DATA_BY_IDENTIFIER = 0x2E,
    UDS_SERVICE_INPUT_OUTPUT_CONTROL_BY_IDENTIFIER = 0x2F,
    UDS_SERVICE_ROUTINE_CONTROL = 0x31,
    UDS_SERVICE_REQUEST_DOWNLOAD = 0x34,
    UDS_SERVICE_REQUEST_UPLOAD = 0x35,
    UDS_SERVICE_TRANSFER_DATA = 0x36,
    UDS_SERVICE_REQUEST_TRANSFER_EXIT = 0x37,
    UDS_SERVICE_REQUEST_FILE_TRANSFER = 0x38,
    UDS_SERVICE_TESTER_PRESENT = 0x3E
} UDSService;

// sub function for UDS_SERVICE_READ_DTC_INFORMATION
typedef enum {
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_DTC_BY_STATUS_MASK              = 0x01,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_BY_STATUS_MASK                        = 0x02,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_SNAPSHOT_IDENTIFICATION               = 0x03,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_SNAPSHOT_RECORD_BY_DTC_NUMBER         = 0x04,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_STORED_DATA_BY_RECORD_NUMBER          = 0x05,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_EXTENDED_DATA_RECORD_BY_DTC_NUMBER    = 0x06,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_DTC_BY_SEVERITY_MASK_RECORD     = 0x07,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_BY_SEVERITY_MASK_RECORD               = 0x08,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_SEVERITY_INFORMATION_OF_DTC               = 0x09,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_SUPPORTED_DTC                             = 0x0A,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_FIRST_FAILED_DTC                          = 0x0B,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_FIRST_CONFIRMED_DTC                       = 0x0C,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MOST_RECENT_FAILED_DTC                    = 0x0D,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MOST_RECENT_CONFIRMED_DTC                 = 0x0E,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MIRROR_MEMORY_DTC_BY_STATUS_MASK          = 0x0F,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MIRROR_MEMORY_DTC_BY_DTC_NUMBER           = 0x10,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_MIRROR_MEMORY_DTC_BY_STATUS_MASK= 0x11,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_EMISSIONS_OBD_DTC_BY_STATUS_MASK= 0x12,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_EMISSIONS_OBD_DTC_BY_STATUS_MASK          = 0x13,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_FAULT_DETECTION_COUNTER               = 0x14,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_WITH_PERMANENT_STATUS                 = 0x15,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_EXTENDED_DATA_RECORD_BY_RECORD_NUMBER = 0x16,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_USER_DEFINED_MEMORY_DTC_BY_STATUS_MASK     = 0x17,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_USER_DEFINED_MEMORY_DTC_SNAPSHOT_BY_NUMBER = 0x18,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_USER_DEFINED_MEMORY_DTC_RECORD_BY_NUMBER   = 0x19,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_WWH_OBD_DTC_BY_STATUS_MASK_RECORD          = 0x42,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_WWH_OBD_DTCS_WITH_PERMANENT_STATUS         = 0x55
} UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION;

#define UDS_NEGATIVE_RESPONSE OBD_DIAGNOSTIC_SERVICE_NEGATIVE_RESPONSE
#define UDS_POSITIVE_RESPONSE OBD_DIAGNOSTIC_SERVICE_POSITIVE_RESPONSE

typedef enum {
    UDS_NRC_GENERAL_REJECT = 0x10,
    UDS_NRC_SERVICE_NOT_SUPPORTED = 0x11,
    UDS_NRC_SUBFUNCTION_NOT_SUPPORTED = 0x12,
    UDS_NRC_INVALID_MESSAGE_LENGTH = 0x13,
    UDS_NRC_RESPONSE_TOO_LONG = 0x14,
    UDS_NRC_BUSY_REPEAT_REQUEST = 0x21,
    UDS_NRC_CONDITIONS_NOT_CORRECT = 0x22,
    UDS_NRC_REQUEST_SEQUENCE_ERROR = 0x24,
    UDS_NRC_NO_RESPONSE_FROM_SUBNET = 0x25,
    UDS_NRC_FAILURE_PREVENTS_EXECUTION = 0x26,
    UDS_NRC_REQUEST_OUT_OF_RANGE = 0x31,
    UDS_NRC_SECURITY_ACCESS_DENIED = 0x33,
    UDS_NRC_INVALID_KEY = 0x35,
    UDS_NRC_EXCEEDED_NUMBER_OF_ATTEMPTS = 0x36,
    UDS_NRC_REQUIRED_TIME_DELAY_NOT_EXPIRED = 0x37,
    UDS_NRC_UPLOAD_DOWNLOAD_NOT_ACCEPTED = 0x70,
    UDS_NRC_TRANSFER_DATA_SUSPENDED = 0x71,
    UDS_NRC_PROGRAMMING_FAILURE = 0x72,
    UDS_NRC_WRONG_BLOCK_SEQUENCE_COUNTER = 0x73,
    UDS_NRC_REQUEST_RECEIVED_RESPONSE_PENDING = 0x78,
    UDS_NRC_SUBFUNCTION_NOT_SUPPORTED_IN_SESSION = 0x7E,
    UDS_NRC_SERVICE_NOT_SUPPORTED_IN_SESSION = 0x7F,
    UDS_NRC_RPM_TOO_HIGH = 0x81,
    UDS_NRC_RPM_TOO_LOW = 0x82,
    UDS_NRC_ENGINE_RUNNING = 0x83,
    UDS_NRC_ENGINE_NOT_RUNNING = 0x84,
    UDS_NRC_ENGINE_RUN_TIME_TOO_LOW = 0x85,
    UDS_NRC_TEMPERATURE_TOO_HIGH = 0x86,
    UDS_NRC_TEMPERATURE_TOO_LOW = 0x87,
    UDS_NRC_SPEED_TOO_HIGH = 0x88,
    UDS_NRC_SPEED_TOO_LOW = 0x89,
    UDS_NRC_THROTTLE_PEDAL_TOO_HIGH = 0x8A,
    UDS_NRC_THROTTLE_PEDAL_TOO_LOW = 0x8B,
    UDS_NRC_TRANSMISSION_RANGE_NOT_IN_NEUTRAL = 0x8C,
    UDS_NRC_TRANSMISSION_RANGE_NOT_IN_DEAR = 0x8D,
    UDS_NRC_BRAKE_SWITCHES_NOT_CLOSED = 0x8F,
    UDS_NRC_SHIFTER_LEVEL_NOT_IN_PARK = 0x90,
    UDS_NRC_TORK_CONVERTER_CLUTCH_LOCKED = 0x91,
    UDS_NRC_VOLTAGE_TOO_HIGH = 0x92,
    UDS_NRC_VOLTAGE_TOO_LOW = 0x93
} UDS_NRC;

char* uds_service_to_string(final UDSService key);
int uds_service_response(final UDSService key);
char * uds_nrc_to_string(final UDS_NRC nrc);

// UDS Standardized DID
typedef enum {
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_bootSoftwareIdentificationDataIdentifier                = 0xF180,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_applicationSoftwareIdentificationDataIdentifier         = 0xF181,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_applicationDataIdentification                           = 0xF182,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_bootSoftwareFingerprint                                 = 0xF183,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_applicationSoftwareFingerprint                          = 0xF184,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_applicationDataFingerprint                              = 0xF185,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_Active_Diagnostic_Session_Data_Identifier_information   = 0xF186,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_manufacturerSparePartNumber                             = 0xF187,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_manufacturerECUSoftwareNumber                           = 0xF188,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_manufacturerECUSoftwareVersion                          = 0xF189,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_identifierOfSystemSupplier                              = 0xF18A,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_ECUManufacturingDate                                    = 0xF18B,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_ECUSerialNumber                                         = 0xF18C,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_SupportedFunctionnalUnit                                = 0xF18D,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_ManufacturerKitAssemblyPartNumber                       = 0xF18E,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_VIN                                                     = 0xF190,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_system_supplier_ECU_hardware_number                     = 0xF192,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_system_supplier_ECU_hardware_version_number             = 0xF193,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_system_supplier_ECU_software_number                     = 0xF194,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_system_supplier_ECU_software_version_number             = 0xF195,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_exhaust_regulation_type_approval_number                 = 0xF196,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_system_name_engine_type                                 = 0xF197,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_repair_shop_code_tester_serial_number                   = 0xF198,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_programming_date                                        = 0xF199,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_ECU_installation_date                                   = 0xF19D,
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID_ODX_file                                                = 0xF19E
} UDS_SERVICE_READ_DATA_BY_IDENTIFIER_DID;

// WWH-OBD DID
typedef enum {
    UDS_SERVICE_READ_DATA_BY_IDENTIFIER_WWH_OBD_DID_VIN = 0xF802
} UDS_SERVICE_READ_DATA_BY_IDENTIFIER_WWH_OBD_DID;

list_Buffer * uds_read_data_by_identifier(final VehicleIFace * iface, final int did);

// SBF field (second byte after the service byte)
typedef enum {
    UDS_SESSION_DEFAULT = 0x01,
    UDS_SESSION_PROGRAMMING = 0x02,
    UDS_SESSION_EXTENDED_DIAGNOSTIC = 0x03,
    UDS_SESSION_SYSTEM_SAFETY_DIAGNOSTIC = 0x04,
} UDS_SESSION;
/**
 * UDS_SESSION or a byte for ISO/SAE reserved
 */
object_hashmap_Int_Int* uds_request_session(final VehicleIFace * iface, final byte session_type);
bool uds_request_session_cond(final VehicleIFace * iface, final byte session_type);

#endif