#ifndef __UDS_SERVICE_READ_DTC_H
#define __UDS_SERVICE_READ_DTC_H

#include "libautodiag/com/uds/uds.h"
#include "libautodiag/lang/all.h"
#include "libautodiag/com/vehicle_interface.h"
#include "libautodiag/com/obd/obd.h"
#include "libautodiag/model/dtc.h"

// sub function for UDS_SERVICE_READ_DTC_INFORMATION
typedef enum {
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_DTC_BY_STATUS_MASK              = 0x01,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_BY_STATUS_MASK                        = 0x02,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_SNAPSHOT_IDENTIFICATION               = 0x03,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_SNAPSHOT_RECORD_BY_DTC_NUMBER         = 0x04,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_STORED_DATA_BY_RECORD_NUMBER          = 0x05,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_EXTENDED_DATA_RECORD_BY_DTC_NUMBER    = 0x06,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_DTC_BY_SEVERITY_MASK_RECORD     = 0x07,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_BY_SEVERITY_MASK_RECORD               = 0x08,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_SEVERITY_INFORMATION_OF_DTC               = 0x09,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_SUPPORTED_DTC                             = 0x0A,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_FIRST_FAILED_DTC                          = 0x0B,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_FIRST_CONFIRMED_DTC                       = 0x0C,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MOST_RECENT_FAILED_DTC                    = 0x0D,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MOST_RECENT_CONFIRMED_DTC                 = 0x0E,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MIRROR_MEMORY_DTC_BY_STATUS_MASK          = 0x0F,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MIRROR_MEMORY_DTC_BY_DTC_NUMBER           = 0x10,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_MIRROR_MEMORY_DTC_BY_STATUS_MASK= 0x11,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_EMISSIONS_OBD_DTC_BY_STATUS_MASK= 0x12,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_EMISSIONS_OBD_DTC_BY_STATUS_MASK          = 0x13,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_FAULT_DETECTION_COUNTER               = 0x14,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_WITH_PERMANENT_STATUS                 = 0x15,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_EXTENDED_DATA_RECORD_BY_RECORD_NUMBER = 0x16,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_USER_DEFINED_MEMORY_DTC_BY_STATUS_MASK     = 0x17,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_USER_DEFINED_MEMORY_DTC_SNAPSHOT_BY_NUMBER = 0x18,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_USER_DEFINED_MEMORY_DTC_RECORD_BY_NUMBER   = 0x19,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_WWH_OBD_DTC_BY_STATUS_MASK_RECORD          = 0x42,
    UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_WWH_OBD_DTCS_WITH_PERMANENT_STATUS         = 0x55
} UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION;

typedef struct {
    DTC;
    byte status;
} UDS_DTC;

void uds_dtc_dump(final UDS_DTC * dtc);
UDS_DTC * UDS_DTC_new();
UDS_DTC * UDS_DTC_new_from(final SAEJ1979_DTC *dtc);
void UDS_DTC_free(UDS_DTC * dtc);
int UDS_DTC_cmp(final UDS_DTC * e1, final UDS_DTC * e2);
char * UDS_DTC_to_string(final UDS_DTC * dtc);

typedef enum {
    UDS_DTC_STATUS_TestFailed = 0b00000001,
    UDS_DTC_STATUS_TestFailedThisOperationCycle = 0b00000010,
    UDS_DTC_STATUS_PendingDTC = 0b00000100,
    UDS_DTC_STATUS_ConfirmedDTC = 0b00001000,
    UDS_DTC_STATUS_TestNotCompletedSinceLastClear = 0b00010000,
    UDS_DTC_STATUS_TestFailedSinceLastClear = 0b00100000,
    UDS_DTC_STATUS_TestNotCompletedThisOperationCycle = 0b01000000,
    UDS_DTC_STATUS_WarningIndicatorRequested = 0b10000000,
} UDS_DTC_STATUS;

char * uds_dtc_status_to_string(byte status, UDS_DTC_STATUS wanted);

AD_LIST_H_DEEP(UDS_DTC,
    byte Status_Availability_Mask;
    ECU * ecu;
);
AD_LIST_H(list_UDS_DTC);

list_list_UDS_DTC * uds_read_dtc_first_confirmed_dtc(final VehicleIFace * iface);

#endif