#ifndef __AD_UDS_SERVICE_READ_DTC_H
#define __AD_UDS_SERVICE_READ_DTC_H

#include "libautodiag/com/uds/uds.h"
#include "libautodiag/lang/all.h"
#include "libautodiag/com/vehicle_interface.h"
#include "libautodiag/com/obd/obd.h"
#include "libautodiag/model/dtc.h"

// sub function for AD_UDS_SERVICE_READ_DTC_INFORMATION
typedef enum {
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_DTC_BY_STATUS_MASK              = 0x01,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_BY_STATUS_MASK                        = 0x02,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_SNAPSHOT_IDENTIFICATION               = 0x03,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_SNAPSHOT_RECORD_BY_DTC_NUMBER         = 0x04,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_STORED_DATA_BY_RECORD_NUMBER          = 0x05,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_EXTENDED_DATA_RECORD_BY_DTC_NUMBER    = 0x06,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_DTC_BY_SEVERITY_MASK_RECORD     = 0x07,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_BY_SEVERITY_MASK_RECORD               = 0x08,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_SEVERITY_INFORMATION_OF_DTC               = 0x09,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_SUPPORTED_DTC                             = 0x0A,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_FIRST_FAILED_DTC                          = 0x0B,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_FIRST_CONFIRMED_DTC                       = 0x0C,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MOST_RECENT_FAILED_DTC                    = 0x0D,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MOST_RECENT_CONFIRMED_DTC                 = 0x0E,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MIRROR_MEMORY_DTC_BY_STATUS_MASK          = 0x0F,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_MIRROR_MEMORY_DTC_BY_DTC_NUMBER           = 0x10,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_MIRROR_MEMORY_DTC_BY_STATUS_MASK= 0x11,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_NUMBER_OF_EMISSIONS_OBD_DTC_BY_STATUS_MASK= 0x12,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_EMISSIONS_OBD_DTC_BY_STATUS_MASK          = 0x13,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_FAULT_DETECTION_COUNTER               = 0x14,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_WITH_PERMANENT_STATUS                 = 0x15,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_DTC_EXTENDED_DATA_RECORD_BY_RECORD_NUMBER = 0x16,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_USER_DEFINED_MEMORY_DTC_BY_STATUS_MASK     = 0x17,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_USER_DEFINED_MEMORY_DTC_SNAPSHOT_BY_NUMBER = 0x18,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_USER_DEFINED_MEMORY_DTC_RECORD_BY_NUMBER   = 0x19,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_WWH_OBD_DTC_BY_STATUS_MASK_RECORD          = 0x42,
    AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION_WWH_OBD_DTCS_WITH_PERMANENT_STATUS         = 0x55
} AD_UDS_SERVICE_READ_DTC_INFORMATION_SUB_FUNCTION;

AD_OBJECT_H(UDS_DTC,
    DTC;
    byte status;
)
typedef ad_object_UDS_DTC AD_UDS_DTC;

void ad_uds_dtc_dump(final AD_UDS_DTC * dtc);
AD_UDS_DTC * AD_UDS_DTC_new();
AD_UDS_DTC * AD_UDS_DTC_new_from(final SAEJ1979_DTC *dtc);
void AD_UDS_DTC_free(AD_UDS_DTC * dtc);
int AD_UDS_DTC_cmp(final AD_UDS_DTC * e1, final AD_UDS_DTC * e2);
char * AD_UDS_DTC_to_string(final AD_UDS_DTC * dtc);
char * AD_UDS_DTC_explanation(final AD_UDS_DTC * dtc);

typedef enum {
    AD_UDS_DTC_STATUS_TestFailed = 0b00000001,
    AD_UDS_DTC_STATUS_TestFailedThisOperationCycle = 0b00000010,
    AD_UDS_DTC_STATUS_PendingDTC = 0b00000100,
    AD_UDS_DTC_STATUS_ConfirmedDTC = 0b00001000,
    AD_UDS_DTC_STATUS_TestNotCompletedSinceLastClear = 0b00010000,
    AD_UDS_DTC_STATUS_TestFailedSinceLastClear = 0b00100000,
    AD_UDS_DTC_STATUS_TestNotCompletedThisOperationCycle = 0b01000000,
    AD_UDS_DTC_STATUS_WarningIndicatorRequested = 0b10000000,
} AD_UDS_DTC_STATUS;

char * ad_uds_dtc_status_to_string(AD_UDS_DTC_STATUS wanted);

AD_LIST_H_DEEP(AD_UDS_DTC,
    byte Status_Availability_Mask;
    ad_object_ECU * ecu;
);
AD_LIST_H(ad_list_AD_UDS_DTC);

ad_list_ad_list_AD_UDS_DTC * ad_uds_read_dtc_by_status_mask(final VehicleIFace * iface, final Vehicle * filter, final byte StatusMask);
ad_list_ad_list_AD_UDS_DTC * ad_uds_read_dtc_first_confirmed_dtc(final VehicleIFace * iface, final Vehicle * filter);
/**
 * No matter if they're confirmed, report any DTC
 */
ad_list_AD_UDS_DTC * ad_uds_read_all_dtcs(final VehicleIFace * iface, final Vehicle * filter);

#endif