name: build deb

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:xenial-20210611
    steps:
      - name: Check
        uses: actions/checkout@v2
      - name: Install build
        run: |
          apt-get update
          apt-get install -y build-essential debhelper dh-make devscripts libgtk-3-0 libgtk-3-dev
      - name: Forced fetch
        continue-on-error: true
        run: |
          git clone https://github.com/autodiag2/database data
      - name: Submodule fetch
        continue-on-error: true
        run: |
          git submodule update --init --recursive
      - name: Build pkg
        run: |
          dpkg-buildpackage -b -us -uc
      - name: find package
        id: find_pkg
        run: |
          package_file=$(readlink -f "../*.deb")
          echo "package_file=${package_file}" >> $GITHUB_OUTPUT
          echo "tag_name=$(echo $GITHUB_REF | sed 's|refs/tags/||')" >> $GITHUB_OUTPUT
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: ${{ steps.find_pkg.outputs.package_file }}
          retention-days: 1
      - name: Move to release
        id: upload-artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find_pkg.outputs.package_file }}
          tag_name: ${{ steps.find_pkg.outputs.tag_name }}
          name: Release ${{ steps.find_pkg.outputs.tag_name }}
          token: ${{ secrets.TOKEN }}
          draft: false
          prerelease: false
